const frenchAnimals = [
  { dog: 'un chien' },
  { cat: 'un chat' },
  { goldfish: 'un poisson rouge' },
  { 'guinea pig': "un cochon d'Inde" },
  { rabbit: 'un lapin' },
  { mouse: 'une souris' },
  { parrot: 'un perroquet' },
  { hamster: 'un hamster' },
  { horse: 'un cheval' },
  { snake: 'un serpent' },
  { cow: 'une vache' },
  { bull: 'un taureau' },
  { sheep: 'un mouton' },
  { goat: 'une chèvre' },
  { hen: 'une poule' },
  { duck: 'un canard' },
  { donkey: 'un âne' },
  { toad: 'un crapaud' },
  { frog: 'une grenouille' },
  { turtle: 'une tortue' },
  { bear: 'un ours' },
  { tiger: 'un tigre' },
  { monkey: 'un singe' },
  { gorilla: 'un gorille' },
  { camel: 'un chameau' },
  { hippopotamus: 'un hippopotame' },
  { hedgehog: 'un hérisson' },
  { platypus: 'un ornithorynque' },
  { ferret: 'un furet' }
];
