const frenchAnimals = [
  { en: 'ant', fr: 'la fourmi' },
  { en: 'bear', fr: "l'ours" },
  { en: 'bee', fr: 'la abeille' },
  { en: 'bull', fr: 'le taureau' },
  { en: 'butterfly', fr: 'le papillon' },
  { en: 'camel', fr: 'le chameau' },
  { en: 'cat', fr: 'le chat' },
  { en: 'cow', fr: 'la vache' },
  { en: 'crab', fr: 'le crabe' },
  { en: 'deer', fr: 'le cerf' },
  { en: 'dog', fr: 'le chien' },
  { en: 'donkey', fr: "l'âne" },
  { en: 'dove', fr: 'la colombe' },
  { en: 'duck', fr: 'le canard' },
  { en: 'elephant', fr: 'le éléphant' },
  { en: 'ferret', fr: 'le furet' },
  { en: 'fox', fr: 'le renard' },
  { en: 'frog', fr: 'la grenouille' },
  { en: 'goat', fr: 'la chèvre' },
  { en: 'goldfish', fr: 'le poisson rouge' },
  { en: 'gorilla', fr: 'le gorille' },
  { en: 'guinea pig', fr: "le cochon d'Inde" },
  { en: 'hamster', fr: 'le hamster' },
  { en: 'hedgehog', fr: 'le hérisson' },
  { en: 'hen', fr: 'la poule' },
  { en: 'hippopotamus', fr: "l'hippopotame" },
  { en: 'horse', fr: 'le cheval' },
  { en: 'jellyfish', fr: 'la méduse' },
  { en: 'kangaroo', fr: 'le kangourou' },
  { en: 'lion', fr: 'le lion' },
  { en: 'monkey', fr: 'le singe' },
  { en: 'mosquito', fr: 'le moustique' },
  { en: 'mouse', fr: 'la souris' },
  { en: 'owl', fr: 'le hibou' },
  { en: 'parrot', fr: 'le perroquet' },
  { en: 'penguin', fr: 'le manchot' },
  { en: 'platypus', fr: "l'ornithorynque" },
  { en: 'rabbit', fr: 'le lapin' },
  { en: 'seahorse', fr: "l'hippocampe" },
  { en: 'seal', fr: 'le phoque' },
  { en: 'shark', fr: 'le requin' },
  { en: 'sheep', fr: 'le mouton' },
  { en: 'snake', fr: 'le serpent' },
  { en: 'spider', fr: "l'araignée" },
  { en: 'squirrel', fr: "l'écureuil" },
  { en: 'swan', fr: 'le cygne' },
  { en: 'tiger', fr: 'le tigre' },
  { en: 'toad', fr: 'le crapaud' },
  { en: 'turtle', fr: 'la tortue' },
  { en: 'walrus', fr: 'le morse' },
  { en: 'wasp', fr: 'la guêpe' },
  { en: 'whale', fr: 'la baleine' },
  { en: 'zebra', fr: 'le zèbre' }
];

const germanAnimals = [
  { en: 'ant', de: 'die Ameise' },
  { en: 'bear', de: 'der Bär' },
  { en: 'bee', de: 'die Biene' },
  { en: 'bull', de: 'der Stier' },
  { en: 'butterfly', de: 'der Schmetterling' },
  { en: 'camel', de: 'das Kamel' },
  { en: 'cat', de: 'die Katze' },
  { en: 'cow', de: 'die Kuh' },
  { en: 'crab', de: 'die Krabbe' },
  { en: 'deer', de: 'der Hirsch' },
  { en: 'dog', de: 'der Hund' },
  { en: 'donkey', de: 'der Esel' },
  { en: 'dove', de: 'die Weiße Taube' },
  { en: 'duck', de: 'die Ente' },
  { en: 'elephant', de: 'der Elefant' },
  { en: 'ferret', de: 'das Frettchen' },
  { en: 'fox', de: 'der Fuchs' },
  { en: 'frog', de: 'der Frosch' },
  { en: 'goat', de: 'die Ziege' },
  { en: 'goldfish', de: 'der Goldfisch' },
  { en: 'gorilla', de: 'der Gorilla' },
  { en: 'guinea pig', de: 'das Meerschwein' },
  { en: 'hamster', de: 'der Hamster' },
  { en: 'hedgehog', de: 'der Igel' },
  { en: 'hen', de: 'das Huhn' },
  { en: 'hippopotamus', de: 'das Flusspferd' },
  { en: 'horse', de: 'das Pferd' },
  { en: 'jellyfish', de: 'die Qualle' },
  { en: 'kangaroo', de: 'das Känguru' },
  { en: 'lion', de: 'der Löwe' },
  { en: 'monkey', de: 'der Affe' },
  { en: 'mosquito', de: 'der Moskito' },
  { en: 'mouse', de: 'die Maus' },
  { en: 'owl', de: 'die Eule' },
  { en: 'parrot', de: 'der Papagei' },
  { en: 'penguin', de: 'der Pinguin' },
  { en: 'platypus', de: 'das Schnabeltier' },
  { en: 'rabbit', de: 'das Kaninchen' },
  { en: 'seahorse', de: 'das Seepferdchen' },
  { en: 'seal', de: 'die Robbe' },
  { en: 'shark', de: 'der Hai' },
  { en: 'sheep', de: 'das Schaf' },
  { en: 'snake', de: 'die Schlange' },
  { en: 'spider', de: 'die Spinne' },
  { en: 'squirrel', de: 'das Eichhörnchen' },
  { en: 'swan', de: 'der Schwan' },
  { en: 'tiger', de: 'der Tiger' },
  { en: 'toad', de: 'die Kröte' },
  { en: 'turtle', de: 'die Schildkröte' },
  { en: 'walrus', de: 'das Walross' },
  { en: 'wasp', de: 'die Wespe' },
  { en: 'whale', de: 'der Wal' },
  { en: 'zebra', de: 'das Zebra' }
];

const italianAnimals = [
  { en: 'ant', it: 'La formica' },
  { en: 'bear', it: "L'orso" },
  { en: 'bee', it: "L'ape" },
  { en: 'bull', it: 'Il toro' },
  { en: 'butterfly', it: 'La farfalla' },
  { en: 'camel', it: 'Il cammello' },
  { en: 'cat', it: 'Il gatto' },
  { en: 'cow', it: 'La mucca' },
  { en: 'crab', it: 'Il granchio' },
  { en: 'deer', it: 'Il cervo' },
  { en: 'dog', it: 'Il cane' },
  { en: 'donkey', it: "L'asino" },
  { en: 'dove', it: 'La colomba' },
  { en: 'duck', it: "L'anatra" },
  { en: 'elephant', it: "L'elefante" },
  { en: 'ferret', it: 'Il furetto' },
  { en: 'fox', it: 'La volpe' },
  { en: 'frog', it: 'La rana' },
  { en: 'goat', it: 'La capra' },
  { en: 'goldfish', it: 'Il pesce rosso' },
  { en: 'gorilla', it: 'Il gorilla' },
  { en: 'guinea pig', it: "Il porcellino d'India" },
  { en: 'hamster', it: 'Il criceto' },
  { en: 'hedgehog', it: 'Il riccio' },
  { en: 'hen', it: 'La gallina' },
  { en: 'hippopotamus', it: "L'ippopotamo" },
  { en: 'horse', it: 'Il cavallo' },
  { en: 'jellyfish', it: 'La medusa' },
  { en: 'kangaroo', it: 'Il canguro' },
  { en: 'lion', it: 'Il leone' },
  { en: 'monkey', it: 'La scimmia' },
  { en: 'mosquito', it: 'La zanzara' },
  { en: 'mouse', it: 'Il topo' },
  { en: 'owl', it: 'Il gufo' },
  { en: 'parrot', it: 'Il pappagallo' },
  { en: 'penguin', it: 'Il pinguino' },
  { en: 'platypus', it: "l'ornitorinco" },
  { en: 'rabbit', it: 'Il coniglio' },
  { en: 'seahorse', it: 'Il cavalluccio marino' },
  { en: 'seal', it: 'La foca' },
  { en: 'shark', it: 'Lo squalo' },
  { en: 'sheep', it: 'La pecora' },
  { en: 'snake', it: 'Il serpente' },
  { en: 'spider', it: 'Il ragno' },
  { en: 'squirrel', it: 'Lo scoiattolo' },
  { en: 'swan', it: 'Il cigno' },
  { en: 'tiger', it: 'La tigre' },
  { en: 'toad', it: 'Il rospo' },
  { en: 'turtle', it: 'La tartaruga' },
  { en: 'walrus', it: 'Il tricheco' },
  { en: 'wasp', it: 'La vespa' },
  { en: 'whale', it: 'La balena' },
  { en: 'zebra', it: 'La zebra' }
];
